# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mindtest_pb2 as mindtest__pb2


class ServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.web_to_server = channel.unary_unary(
                '/mindtest.Server/web_to_server',
                request_serializer=mindtest__pb2.WebToServiceRequest.SerializeToString,
                response_deserializer=mindtest__pb2.WebToServiceResponse.FromString,
                )
        self.server_to_web = channel.unary_unary(
                '/mindtest.Server/server_to_web',
                request_serializer=mindtest__pb2.ServiceToWebRequest.SerializeToString,
                response_deserializer=mindtest__pb2.ServiceToWebResponse.FromString,
                )


class ServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def web_to_server(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def server_to_web(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'web_to_server': grpc.unary_unary_rpc_method_handler(
                    servicer.web_to_server,
                    request_deserializer=mindtest__pb2.WebToServiceRequest.FromString,
                    response_serializer=mindtest__pb2.WebToServiceResponse.SerializeToString,
            ),
            'server_to_web': grpc.unary_unary_rpc_method_handler(
                    servicer.server_to_web,
                    request_deserializer=mindtest__pb2.ServiceToWebRequest.FromString,
                    response_serializer=mindtest__pb2.ServiceToWebResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mindtest.Server', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Server(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def web_to_server(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mindtest.Server/web_to_server',
            mindtest__pb2.WebToServiceRequest.SerializeToString,
            mindtest__pb2.WebToServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def server_to_web(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mindtest.Server/server_to_web',
            mindtest__pb2.ServiceToWebRequest.SerializeToString,
            mindtest__pb2.ServiceToWebResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
